apiVersion: 1

datasources:
  - name: TradingDB
    type: postgres
    url: postgres:5432
    user: trading_user
    secureJsonData:
      password: trading_pass
    jsonData:
      database: trading_db
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
